### ISSUE TITLE
Не пересоздавать весь контент адаптера при добавлении элемента

### ISSUE THREAD

**Issue by govorovsky** [AntonOcean/android-app-simple#1]
https://github.com/AntonOcean/android-app-simple/blob/7e47e571e3a66a85f6d71456dd1ac60064cc04d6/app/src/main/java/com/github/antonocean/numbers/NumberAdapter.java#L34

Переписать логику добавления элемента на использование notifyItemInserted()

**Comment by AntonOcean** [comment]
Исправлено

**Comment by AntonOcean** [comment]
Спасибо большое, исправил.С уважением,Цитульский Антон19.10.2019, 02:01, "Andrey Govorovsky" <notifications@github.com>:https://github.com/AntonOcean/android-app-simple/blob/7e47e571e3a66a85f6d71456dd1ac60064cc04d6/app/src/main/java/com/github/antonocean/numbers/NumberAdapter.java#L34
Переписать логику добавления элемента на использование notifyItemInserted()
